# Permalinks
permalink:           pretty

# Setup
exclude:             [CNAME, Gemfile, README.md, LICENSE.md, scratch.md]
unpublished:         true
show_drafts:         false
title:               'Lanyon Wishlist'
tagline:             'Lanyon + requests from users'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>, extended by its fans and users.'
url:                 'http://lanyon.getpoole.com'
baseurl:             ''

# About/contact
author:
  name:              'Joe Friedrichsen'
  url:               'https://github.com/wireddown/wireddown.github.io/tree/upstream-wishlist'
  email:             'wireddown@users.noreply.github.com'

# Custom vars
version:             1.1.0
